#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

rm -r case*.tar

rm -r deltaT.txt
rm -r res.txt
rm -r Time.txt

rm -rf postProcessing
rm -rf logs

rm -r output_bubble_analysis


#------------------------------------------------------------------------------